### ISSUE TITLE
Why is default_cookie_jar not exported?

### ISSUE THREAD

**Issue by MihaMarkic** [flutterchina/cookie_jar#10]
I'd like to read/write cookies from default_cookie_jar, but I have to explicitly reference the file
```dart
import 'package:cookie_jar/src/default_cookie_jar.dart';
```

instead of referencing just the package

```dart
import "package:cookie_jar/cookie_jar.dart";
```

It works, but then dart yields a warning not to reference files from packages directly.

**Comment by wendux** [comment]
fixed! please update to latest version
