### ISSUE TITLE
The setter 'cookieJar' isn't defined for the class 'Dio'.

### ISSUE THREAD

**Issue by AlexVincent525** [flutterchina/cookie_jar#11]
你好，目前在使用cookiejar与dio配合时，设置cookirJar出现如下错误提示：`The setter 'cookieJar' isn't defined for the class 'Dio'.`
![image](https://user-images.githubusercontent.com/15884415/54593505-ac0c0080-4a69-11e9-914a-f44e81214e1a.png)

各依赖版本 (Packages' Version): 
`cookie_jar: ^1.0.0`
`dio: ^2.1.0`

代码 (Code) : 
```dart
import 'dart:async';
import 'package:dio/dio.dart';
import 'package:cookie_jar/cookie_jar.dart';

class NetUtils {
  static Future<String> get(String url, queryParameters) async {
    Dio dio = new Dio();
    dio.cookieJar = new PersistCookieJar(dir:"./cookies");
    Response response = await dio.get(url);
    return response.toString();
  }
}
```

**Comment by wendux** [comment]
dio 2.0后， cookie管理方式有了变化， 可以参考https://github.com/flutterchina/dio#cookie-manager

**Comment by 15202284857** [comment]
你好,具体怎么变化的能说下吗,你的参考地址我没有看到相关的变化的地方
