### ISSUE TITLE
Cookies are not sent to subdomains

### ISSUE THREAD

**Issue by kbrz** [flutterchina/cookie_jar#16]
If cookie is set for `https://sub1.domain.com` it should be also loaded for `https://sub2.domain.com` (as described in https://tools.ietf.org/html/rfc6265#section-4.1.2.3). Now DefaultCookieJar is not working this way.

**Comment by omidh28** [comment]
Is there any solution? I really need cross domain cookies

**Comment by wendux** [comment]
You can specify the root domain attribute to `Cookie`. for example (cookie_jar version 3.0.0-beta2):
```dart
  test('SharedCookie', () async {
    final cj = CookieJar();
    final cookies = <Cookie>[
      Cookie('name', 'wendux')..domain = '.facebook.com',
      Cookie('location', 'china')..domain = 'qq.com',
    ];
    await cj.saveFromResponse(Uri.parse('https://www.facebook.com/tt'), cookies);
    final results = await cj.loadForRequest(Uri.parse('https://tt.facebook.com/xxx'));
    expect(results.length, 1);
  });
```
