### ISSUE TITLE
Possibly a security vulnerability, cookies in one cookie jar are currently visible in all cookie jars

### ISSUE THREAD

**Issue by a9udn9u** [flutterchina/cookie_jar#17]
In the `DefaultCookieJar` class, cookies are saved in a private member `_domains`, which is currently [`static`](https://github.com/flutterchina/cookie_jar/blob/master/lib/src/default_cookie_jar.dart#L20-L28), meaning all `DefaultCookieJar` instances share the same cookie storage.

Is there any reason behind this decision or is it a bug? Seems like a potential security vulnerability to me.

**Comment by wendux** [comment]
Cookies are domain-related, and cookies under the same domain name are shared。So we use a singleton to make it.
