### ISSUE TITLE
Option to store cookie using shared_preference

### ISSUE THREAD

**Issue by kateile** [flutterchina/cookie_jar#20]
I think lib should option for cookies storage. So as programmer may choose to store cookies in either files or using libs like [shared_preference ](https://pub.dev/packages/shared_preferences) or [flutter_secure_storage](https://github.com/mogol/flutter_secure_storage).

If this sounds good to you maybe I could open PR.

**Comment by wendux** [comment]
Well，just do it !

**Comment by wendux** [comment]
It is supported in 3.0.0-beta2,  [Here](https://github.com/flutterchina/cookie_jar/blob/dev/lib/src/file_stroage.dart) is an example.

**Comment by kateile** [comment]
I am thinking of using Hive for cookie storage and flutter_secure_storage for storing key. I  am wondering what to write in  `init method` @wendux can you comment anything on this

```dart
main() async {
  await Hive.initFlutter();
  final box = await Hive.openBox('name');

  final jar = HiveCookieJar(box);
  ///.........
}

///Save cookies in  files
class HiveCookieJar implements Storage {
  HiveCookieJar(this.box);

  /// Box which will be used for cookie storage
  Box box;

  @override
  Future<void> init(bool persistSession, bool ignoreExpires) async {}

  @override
  Future<void> write(String key, String value) {
    return box.put(key, value);
  }

  @override
  Future<String?> read(String key) {
    return box.get(key);
  }

  @override
  Future<void> delete(String key) {
    return box.delete(key);
  }

  @override
  Future<void> deleteAll(List<String> keys) {
    return box.deleteAll(keys);
  }
}
```

**Comment by wendux** [comment]
`init` will be called  when `persistSession` or ` ignoreExpires` changes. If you really don't need `init` action，just ignore it.
