### ISSUE TITLE
Are cookies encrypted in case of PersistCookieJar?

### ISSUE THREAD

**Issue by shujaatak** [flutterchina/cookie_jar#23]
I wonder if cookies are encrypted in case of PersistCookieJar or not?

**Comment by wendux** [comment]
It is supported in 3.0.0-beta2(preview version)，and there is an example https://github.com/flutterchina/cookie_jar/blob/dev/example/encryption.dart

**Comment by wsdqr001** [comment]
According to my test, 4.0.8 still does not have the encryption function, so how can i encrypt cookies?
