### ISSUE TITLE
Does it support for web?

### ISSUE THREAD

**Issue by githubtuxedo** [flutterchina/cookie_jar#26]
Does it support for web?

**Comment by motu2119** [comment]
Same question for me.

**Comment by unacorbatanegra** [comment]
The library doesn't have support yet, bc dart:html does not provide a core class the the library need,
let's see how they handle it

**Comment by juanagu** [comment]
any update around it?

**Comment by wendux** [comment]
NO, because the browser will automatically manage cookies.

**Comment by provokateurin** [comment]
The problem is that it's not possible to use this library on web since it depends on io. It would be nice if that dependency could be abstracted away so that it's possible to use this library both on io and web.

**Comment by unacorbatanegra** [comment]
The browser automatically manage the cookies.

**Comment by provokateurin** [comment]
Yes I know, but I have a library I want to use on both io and web, but having to import the cookie_jar library breaks it on web because it imports dart:io.

**Comment by AlexV525** [comment]
The plugin should also support compiling with Web now but not be able to call anything.

**Comment by provokateurin** [comment]
Thanks a lot, I'll try it soon.
