### ISSUE TITLE
When installing new version of build, there is issue in android. (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by KanybekMomukeyev** [flutterchina/cookie_jar#32]
```
FileSystemException: FileSystemException: Deletion failed, path = '/data/user/0/com.example.app/app_flutter/.cookies/ie0_ps1/' 
(OS Error: No such file or directory, errno = 2)
```
Crashed in non-app: directory_impl.dart in _Directory._delete.<fn>
file_storage.dart in FileStorage.deleteAll at line 30 within cookie_jar
persist_cookie_jar.dart in PersistCookieJar.deleteAll at line 165 within cookie_jar

**Comment by AlexV525** [comment]
Fixed in 5f04cdd0c69f87cfef9f91ff24c595dcadd054cb.
