### ISSUE TITLE
cookie可以强制保存吗

### ISSUE THREAD

**Issue by sidealice** [flutterchina/cookie_jar#4]
python的cookie在处理是有两个参数可以控制：
ignore_discard: save even cookies set to be discarded. 
ignore_expires: save even cookies that have expiredThe file is overwritten if it already exists

ignore_discard的意思是即使cookies将被丢弃也将它保存下来
ignore_expires的意思 是如果cookies已经过期也将它保存并且文件已存在时将覆盖

不知道库里可以加这两个逻辑吗？

**Comment by wendux** [comment]
@sidealice 目前不支持这两个参数


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wendux** [comment]
已支持！ 可以设置ignoreExpires为true即可。
