### ISSUE TITLE
Creation failed, path = './cookies/' (OS Error: Permission denied, errno = 13) 错误

### ISSUE THREAD

**Issue by SaltedFishkk** [flutterchina/cookie_jar#7]
var cj =  new  CookieJar();    
final List<Cookie> cookies = <Cookie>[
      new Cookie('token', 'token'),
    ];
 cj.saveFromResponse(Uri.parse('http://192.168.43.144:8088/api/work_time/getLis'), cookies);

    Directory tempDir = await getTemporaryDirectory();
    String tempPath = tempDir.path;
    print("kkkk path : "+tempPath);
//   dio.cookieJar =new PersistCookieJar(tempPath);
    dio.cookieJar = PersistCookieJar("./cookies");

我用tempPath 路径获取不到 cookies
然后又试着用./cookies"
报错
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
FileSystemException: Creation failed, path = './cookies/' (OS Error: Permission denied, errno = 13)
#0      _Directory.createSync (dart:io/directory_impl.dart:140:7)
#1      new PersistCookieJar (package:cookie_jar/src/persist_cookie_jar.dart:23:17)
#2      _MyHomePageState.getList (package:flutter_app1/main.dart:106:21)
<asynchronous suspension>
#3      _MyHomePageState.build (package:flutter_app1/main.dart:51:5)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#10     Element.inflateWi<…>

实在是不知道怎么用,求解释

**Comment by SpikeYeh** [comment]
`//Save cookies   
  cj.saveFromResponse(Uri.parse("https://www.baidu.com/"), cookies);
  //Get cookies  
  List<Cookie> results = cj.loadForRequest(Uri.parse("https://www.baidu.com/xx"));`
这是CookieJar的存和取。你用的那个取法是PersistCookieJar。两个不同

**Comment by SaltedFishkk** [comment]
多谢

**Comment by SaltedFishkk** [comment]
> `//Save cookies `
> ` cj.saveFromResponse(Uri.parse("https://www.baidu.com/"), cookies);`
> `//Get cookies `
> `List<Cookie> results = cj.loadForRequest(Uri.parse("https://www.baidu.com/xx"));`
> 这是CookieJar的存和取。你用的那个取法是PersistCookieJar。两个不同

多谢
