### ISSUE TITLE
(OS Error: Permission denied, errno = 1)

### ISSUE THREAD

**Issue by SpikeYeh** [flutterchina/cookie_jar#8]
`Directory tempDir = await getTemporaryDirectory();`
`String tempPath = tempDir.path;`
`CookieJar cj=new PersistCookieJar(tempPath);`
`cj.deleteAll()`//got an error on iOS device iPhone 8 iOS 12.1.1
error： (OS Error: Permission denied, errno = 1)
But it works fine on the simulator & I don't know if Android is the same.

**Comment by wendux** [comment]
这个肯定是路径的问题，可以试试getApplicationDocumentsDirectory(), 最好单独创建一个保存cookie的目录
